config/routes.rb
Rails.application.routes.draw do

  post '/api/login', to: 'plains_walkers#login'

  resources :plains_walkers

  resources :decks

	get '/api/decks/:id', to: 'home#get_deck'
	get '/api/cards/:id', to: "home#get_card"
	get '/api/cards', to: "cards#index"

  root 'home#index'
end



# For Louie's (the person) pleasure. 
# Run '$ rake routes' in your terminal to see all routes also.

# RESTful

# get all     GET '/api/cards'
# get one     GET '/api/cards/:id'

# create one  POST '/api/cards'
# update one  PUT  '/api/cards/:id'
# delete one  DELETE '/api/cards/:id'

app/models/card.rb
class Card < ActiveRecord::Base
	has_many :deck_cards
	has_many :decks, through: :deck_cards
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :plains_walker
  has_many :deck_cards
  has_many :cards, through: :deck_cards

  validates :plains_walker_id, presence: true
end

app/models/deck_card.rb
class DeckCard < ActiveRecord::Base
  belongs_to :deck
  belongs_to :card
end

app/models/plains_walker.rb
class PlainsWalker < ActiveRecord::Base
	has_many :decks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	def index
		if params[:name]
			@cards = Card.where("name LIKE '%" + params[:name] + "%' ")
		else
			@cards = Card.limit(100)
		end
	end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
    if params[:plains_walker_id]
      @decks = Deck.where(plains_walker_id: params[:plains_walker_id])
      @decks.order(last_used: :desc, created_at: :asc)
    end
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        save_deck_cards

        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        save_deck_cards

        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:name, :description, :plains_walker_id)
    end

    def save_deck_cards
      @deck.deck_cards = []
        
      params[:deck][:cards].each do |card|
        @deck.deck_cards << DeckCard.new(card_id: card[:id])
      end

      @deck.deck_cards.each(&:save)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  # API routes
  def get_deck
  	render json: Card.where("id < 61")
  end


  def get_card
  	render json: Card.find(params[:id])
  end

  def get_all_cards
  	render json: Card.all
  end
end

app/controllers/plains_walkers_controller.rb
class PlainsWalkersController < ApplicationController
  before_action :set_plains_walker, only: [:show, :edit, :update, :destroy]

  # GET /plains_walkers
  # GET /plains_walkers.json
  def index
    @plains_walkers = PlainsWalker.all
  end

  # GET /plains_walkers/1
  # GET /plains_walkers/1.json
  def show
  end

  # GET /plains_walkers/new
  def new
    @plains_walker = PlainsWalker.new
  end

  # GET /plains_walkers/1/edit
  def edit
  end

  # POST /plains_walkers
  # POST /plains_walkers.json
  def create
    @plains_walker = PlainsWalker.new(plains_walker_params)

    respond_to do |format|
      if @plains_walker.save
        format.html { redirect_to @plains_walker, notice: 'Plains walker was successfully created.' }
        format.json { render :show, status: :created, location: @plains_walker }
      else
        format.html { render :new }
        format.json { render json: @plains_walker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plains_walkers/1
  # PATCH/PUT /plains_walkers/1.json
  def update
    respond_to do |format|
      if @plains_walker.update(plains_walker_params)
        format.html { redirect_to @plains_walker, notice: 'Plains walker was successfully updated.' }
        format.json { render :show, status: :ok, location: @plains_walker }
      else
        format.html { render :edit }
        format.json { render json: @plains_walker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plains_walkers/1
  # DELETE /plains_walkers/1.json
  def destroy
    @plains_walker.destroy
    respond_to do |format|
      format.html { redirect_to plains_walkers_url, notice: 'Plains walker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login
    plains_walker = PlainsWalker.find_by_name(params[:name])
    
    # 1. Plainswalker name does exist, check if its password is right.
    # 2. Plainswalker name doesnt exist, create him! Or her.
    if plains_walker
      if plains_walker.password == params[:password]
        render json: { success: true, status: "Authentication successful.", plains_walker: plains_walker }
      else
        render json: { success: false, status: "Fuck you, you fucking hackr."}
      end
    else
      # create a new one!
      plains_walker = PlainsWalker.new
      plains_walker.name = params[:name]
      plains_walker.password = params[:password]
      plains_walker.save
      
      render json: { success: true, status: "YOUR JOURNEY BEGINS. PLUTOS A PLANET", plains_walker: plains_walker }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plains_walker
      @plains_walker = PlainsWalker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plains_walker_params
      params.require(:plains_walker).permit(:name, :password, :avatarUrl)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/plains_walkers_helper.rb
module PlainsWalkersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/decks/_form.html.erb
<%= form_for(@deck, class: "form") do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="well">
    <div class="field form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :plains_walker_id %><br>
      <%= f.text_field :plains_walker_id, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/decks/edit.html.erb
<div class="container">
	<h1>
		Editing deck
		<small class="pull-right">
			<%= link_to 'Show', @deck %> |
			<%= link_to 'Back', decks_path %>
		</small>
	</h1>

	<%= render 'form' %>
	<br/>
	<div class="well">
		<h3>CARD SELECTION</h3>
		<form class="form">
			<div class="input-group">
				<span class="input-group-addon" id="sizing-addon1">
					<i class="glyphicon glyphicon-search"></i>
				</span>
				<input 
					type="text" 
					name="searchCards" 
					placeholder="Search cards" 
					class="form-control">
				</input>
			</div>
		</form>
	</div>
</div>

app/views/decks/index.html.erb
<h1>Listing decks</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Plains walker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.name %></td>
        <td><%= deck.description %></td>
        <td><%= deck.plains_walker.name %></td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path %>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<div class="well">
		<p>
		  <strong>Name:</strong>
		  <%= @deck.name %>
		</p>

		<p>
		  <strong>Description:</strong>
		  <%= @deck.description %>
		</p>

		<p>
		  <strong>Plains walker:</strong>
		  <%= @deck.plains_walker.name %>
		</p>
	</div>

	<%= link_to 'Edit', edit_deck_path(@deck) %> |
	<%= link_to 'Back', decks_path %>
</div>

app/views/home/index.html.erb
<div ng-view class="view-frame"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="myApp">
<head>
  <title>black lotus club</title>

  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">

  <script src="https://code.jquery.com/jquery-1.10.1.min.js"></script>
  <script src="https://cdn.blockspring.com/blockspring.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-60229220-1', 'auto');
    ga('send', 'pageview');
  </script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/plains_walkers/_form.html.erb
<%= form_for @plains_walker, class: "form" do |f| %>
  <% if @plains_walker.errors.any? %>
    <div id="error_explanation">
      <h2
        ><%= pluralize(@plains_walker.errors.count, "error") %> prohibited this plains_walker from being saved:
      </h2>

      <ul>
        <% @plains_walker.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :password %><br>
    <%= f.text_field :password, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :avatarUrl %><br>
    <%= f.text_area :avatarUrl, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/plains_walkers/edit.html.erb
<h1>Editing plains_walker</h1>

<%= render 'form' %>

<%= link_to 'Show', @plains_walker %> |
<%= link_to 'Back', plains_walkers_path %>

app/views/plains_walkers/index.html.erb
<div class="container">
  <h1>Listing plains_walkers</h1>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Avatarurl</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @plains_walkers.each do |plains_walker| %>
      <tr>
        <td><%= plains_walker.name %></td>
        <td><img src="<%= plains_walker.avatarUrl %>" height="200"/></td>
        <td>
          <div class="btn-group">
            <%= link_to 'Show', plains_walker, class: "btn btn-default" %>
            <%= link_to 'Edit', edit_plains_walker_path(plains_walker), class: "btn btn-default" %>
            <%= link_to 'Destroy', plains_walker, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
          </div>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Plains walker', new_plains_walker_path, class: "btn btn-primary" %>
</div>

app/views/plains_walkers/new.html.erb
<div class="container">
	<h1>New plains_walker</h1>

	<%= render 'form' %>

	<br/>
	
	<%= link_to 'Back', plains_walkers_path %>
</div>

app/views/plains_walkers/show.html.erb
<p id="notice"><%= notice %></p>

<br/>

<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1>Plainswalker profile</h1>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-sm-3">
          <a href="#" class="thumbnail">
            <img src="<%= @plains_walker.avatarUrl %>" >
          </a>
        </div>
        <div class="col-sm-9">
          <h2><%= @plains_walker.name %></h2>
          <p>Wins: 0</p>
          <p>Losses: 0</p>
          <div class="row">
            <div class="col-sm-12">
              <h4>Decks</h4>
              <hr/>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= link_to 'Edit', edit_plains_walker_path(@plains_walker) %> |
  <%= link_to 'Back', plains_walkers_path %>

</div>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>